# Generated by Django 3.1.2 on 2020-10-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_batata'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_content',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('dollar', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
