# Generated by Django 3.1.2 on 2020-10-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20201015_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_content',
            name='CSV_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.upload'),
            preserve_default=False,
        ),
    ]
