# Generated by Django 3.1.2 on 2020-10-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_file_content_csv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='id',
        ),
        migrations.AddField(
            model_name='upload',
            name='ID',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
