# Generated by Django 3.1.2 on 2020-10-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20201016_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_content',
            name='CSV_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.upload'),
        ),
    ]
