# Generated by Django 3.1.2 on 2020-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20201017_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_content',
            name='CSV_ID',
            field=models.IntegerField(),
        ),
    ]
